GenieClient/Maps

- Copy These to Genie's Scripts Folder/travel.cmd
Fix for odd numbers of ()""[]
fix for missing space after quotes "","" > "", ""
removed space in front of Matchre (
> Fix Gscript formatting in travel.cmd

- Copy These to Genie's Scripts Folder/automapper.cmd
Fix for bad command on line 317 (>>)
> Fix for bad command on line 317

- Copy These to Genie's Scripts Folder/automapper.cmd
Removed RETURN: label and moved logic to MOVE.DONE 
Fixed bugs in Dark Room checks and Light Use
> Automapper Update

- Copy These to Genie's Scripts Folder/automapper.cmd
fixes it so that you can use a script in  action gosub (looks for .)
> Userwalk_for_scripts

- Copy These to Genie's Scripts Folder/automapper.cmd
for those time when someone closes the wall before your slow internet lets the command through
> fix ggbypass edge case

- Copy These to Genie's Scripts Folder/automapper.cmd
> Added missing PUT sub

- Copy These to Genie's Scripts Folder/automapper.cmd
fix for slow access room to shard favors
> fix for slow access room to shard favors

- Copy These to Genie's Scripts Folder/automapper.cmd
Change punch to bob so as to not shock empaths. Try to up balance 2 times for retreating and abort on fail
> retreat update

- Copy These to Genie's Scripts Folder/automapper.cmd
- Copy These to Genie's Scripts Folder/crossingtrainerfix.cmd
new variable controlled waiteval timeout so you don't get hung up forever waiting for wave to collapse
> WaitevalTimeOut

- Copy These to Genie's Scripts Folder/travel.cmd
- Heavily Robustified Ferry (NPC Transportation) Travel
- SHOULD now support starting Travel when ~already on a ferry~
- Should work whether Auto-Disembark is ON or OFF
- When traveling on a ferry, which now Echo the name of the Transport
> Travel 5.2.3

- Copy These to Genie's Scripts Folder/travel.cmd
> Travel 5.2.4

- Map150_Fang_Cove.xml
added that missing room
shifted some rooms around to not be so cluttered
> Fang's Rise, Secluded Island

- Copy These to Genie's Scripts Folder/travel.cmd
> Travel v5.2.5

- Copy These to Genie's Scripts Folder/automapper.cmd
proper caps on all LABELS and goto/gosub/matchre LABEL
also some bullshit for outlander bugs that won't affect genie
> cap labels

- Map4_Crossing_West_Gate.xml
- Map50_Segoltha_River.xml
Both clans are temporarily inaccessible due to current story arc.
> Update entrance to Wolf Clan and Tiger Clan

- Map90f_Basalt_Isle.xml
Add post office to Carousel, lowercase notes, remove notes that are just room name duplicates.
> Add Post Office, Update Notes

- Map7_NTR.xml
Dirge is current inaccessible due to world story arc.
> Update entrance to Dirge

- Map7_NTR.xml
Dirge is now accessible again as a result of ongoing story arc.
> Reconnect Dirge to NTR

- Copy These to Genie's Scripts Folder/automapper.cmd
- Copy These to Genie's Scripts Folder/crossingtrainerfix.cmd
- Copy These to Genie's Scripts Folder/ggbypass.cmd
- Copy These to Genie's Scripts Folder/hibintelligence.cmd
- Copy These to Genie's Scripts Folder/infusionentry.cmd
- Copy These to Genie's Scripts Folder/peerchurch.cmd
- Copy These to Genie's Scripts Folder/sandspit.cmd
- Copy These to Genie's Scripts Folder/sharddetour.cmd
- Copy These to Genie's Scripts Folder/speedtest.cmd
- Copy These to Genie's Scripts Folder/travel.cmd
- Map12a_Misenseor_Abbey.xml
also and added spacing to matchre
> changed all = to ==

- Copy These to Genie's Scripts Folder/travel.cmd
Robustified FERRY travel FROM Ratha TO MAINLAND for NON-PREMIUM PRIME users Will try taking MAMMOTHS first, if no mammoth, will go to Skirr'lolasu If no Skirr'lolasu found, it should go back to Mammoths and just wait for them
> Travel 5.2.9

- Copy These to Genie's Scripts Folder/automapper.cmd
Please run back and forth between rooms 2 and 20 a few times to make sure I've not messed this up for Genie
> fix for shift error on mistwood cliff

- Copy These to Genie's Scripts Folder/automapper.cmd
- Map106_Hara'jaal.xml
- Map108_M'Riss.xml
- Map4a_Tiger_Clan.xml
- Map67_Shard.xml
- Map7_NTR.xml
- Map90_Ratha.xml
- Map92_Ratha_NW.xml
- Map98_Road_to_Aesry.xml
- Map9b_Sorrow's_Reach.xml
search for hidden paths now has a more robust handling, paths updated in maps where I tested them.
> Action search

- Copy These to Genie's Scripts Folder/automapper.cmd
- Map68_Shard_South_Gate.xml
> something is wrong with room195

- Map116_Hibarnhvidar.xml
> Map116_Hibarnhvidar

- Copy These to Genie's Scripts Folder/travel.cmd
- Changed most leftover PUT <DIRECTION> commands to GOSUB MOVE <DIRECTION>
- Changed "FORD" label to "FORF"
- Robustified several checks for GAME = DR so it doesn't false positive on other game instances
- Various other tweaks and code cleanup
> Travel 5.3

- Copy These to Genie's Scripts Folder/automapper.cmd
- Map107_Mer'Kresh.xml
- Map116_Hibarnhvidar.xml
- Map1_Crossing.xml
- Map30_Riverhaven.xml
- Map40_Langenfirth_to_Therenborough.xml
- Map47_Muspar'i.xml
- Map67_Shard.xml
- Map90_Ratha.xml
- Map99_Aesry_Surlaenis'a.xml
> Laego updates

- Map90_Ratha.xml
Added Forge - Bulk Material Shop. Added missing Warrior Mage Guild - Back Area.
> Update - Map90 -Ratha - Forge Bulk/ Warmage Guild missing rooms

- Hollow_Eve.xml
-- Fix room description in All The Kings Men, Belts room. -- Add additional descriptions in two rooms of the Haunted House. -- Add additional description to Hot Tropics, Sunkissed Sands
> Various room description updates

- Hollow_Eve.xml
Add alternate room description to Riptide Roasters, Brightwater Blend.
> Add alternate room desc for shop

- Map1_Crossing.xml
Fix missing GO when leaving Map 1 room 380.
> Fix missing GO

- Copy These to Genie's Scripts Folder/travel.cmd
Fixed several bad checks for NOT TF which would cause infinite loops for PLAT users in some areas
> Travel 5.3.1

- Map62_STR2.xml
- Map7_NTR.xml
Dantia Help me out with room 851
Also let's fix it so we default to the non-wounded way out.
> TT261 Onxy Gargs

- Map7_NTR.xml
Added giant bears and onyx gargoyles expansion from Tuesday's Tidings 257 and 261.
> Added giant bears and onyx gargoyles expansion from TT.

- Map90_Ratha.xml
> The Rusted Tumbler

- Map4_Crossing_West_Gate.xml
Arnack's Tavern, Mud Pit
Arnack's Tavern, Washroom
Arnack's Tavern, Wooden Tub
> updated Arnack's Tavern

- Map116_Hibarnhvidar.xml
- Map127_Boar_Clan.xml
- Map1_Crossing.xml
- Map67_Shard.xml
- Map69_Shard_West_Gate.xml
I primarily just added some missing (alternate) room descriptions, but there is one room in Boar Clan that was missing.
> minor map tweaks in P3/P5
